[package]
name = "rust_sh"
version = "0.1.0"
authors = ["mrbluesky2 <pierrecarr2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
